### ISSUE TITLE
Accept JSCSRC files

### ISSUE THREAD

**Issue by gavinr** [jdavisclark/JsFormat#151]
Seems like [JSCS](http://jscs.info/) is a more commonly understood and more actively developed style linter than jsbeautify. Are there plans to accept .jscsrc files instead of jsbeautifyrc files?

**Comment by jdc0589** [comment]
It isn't planned, but I wouldn't be opposed to a pull request that added configurable support for them (keeping support for jsbeautifyrc files). JsBeautifier isn't a linter, and not everything is configurable, so only a very small portion of JSCSRC settings are likely to be applicable.

**Comment by BryanH** [comment]
According to [their website](https://jscs-dev.github.io/), JSCS has merged with ESLint
