### ISSUE TITLE
Package Control  install JsFormat,but not found.

### ISSUE THREAD

**Issue by mingetian** [jdavisclark/JsFormat#188]
https://codeload.github.com/jdc0589/JsFormat/zip/master download prompt 404(Not Found).

**Comment by tobiasdiez** [comment]
I still get this error when installing: 
```
Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/jdc0589/JsFormat/zip/master.
````

**Comment by bitwiseman** [comment]
@tobiasdiez See https://github.com/jdavisclark/JsFormat#install
