### ISSUE TITLE
Update js-beautify to 1.8.x (or 1.9.x)

### ISSUE THREAD

**Issue by bitwiseman** [jdavisclark/JsFormat#189]
1.8.x has been out for a while.  1.9.0 will be out soon.  We should update.

**Comment by BryanH** [comment]
Usually only makes sense to update when there have been significant changes

**Comment by sgerace** [comment]
I'd like to see jsbeautify updated in order to address https://github.com/jdavisclark/JsFormat/issues/193

**Comment by sgerace** [comment]
Any chance we can move to 1.10.x or greater to incorporate this fix: https://github.com/beautify-web/js-beautify/issues/1734?

**Comment by sgerace** [comment]
I've created a pull request to incorporate the latest version of js-beautify.
