### ISSUE TITLE
indentation for chained methods

### ISSUE THREAD

**Issue by coderbarncb** [jdavisclark/JsFormat#19]
Would it be possible to add an option like
"method_chaining_indentation": "number"
where 
- number = 0 would mean keeping the current functionality
- number = 4 would mean indent the chained command by 4 spaces

Examples:
Current:
someObject.doFoo(x).doBar(y).doBaz(z);
Indented (better readability):
someObject.doFoo(x)
    .doBar(y)
    .doBaz(z);

Thanks,
Chris

**Comment by jshjohnson** [comment]
What is the name of this option?
