### ISSUE TITLE
Property with name ´default´ is formatted in a new line

### ISSUE THREAD

**Issue by rmariuzzo** [jdavisclark/JsFormat#89]
Some colleagues at work and me use this plugin a lot in Sublime Text 3, but lately I noticed a behavior that could be wrong.

If have the following code:

```
Handlebars.default.compile("hello world");
```

The formatted results is:

```
Handlebars.
default.compile("hello");
```

It only appears to happen when using a property with name `default`, maybe it collide with JS keyword.

**Comment by 0x80** [comment]
Could someone please explain to me how to get this fix into sublime text? I've added both the JsFormat and JsBeautify repositories to my sublime with "Add repository", but I get no upgrades listed and keywords like "finally" are still treated as reserved keywords.

**Comment by jdc0589** [comment]
@0x80 you don't need to do either of those things. JsFormat comes with the JsBeautify dependency packaged up, you don't need to worry about it. JsFormat is also in the default Package Control channel, so you should not have had to manually add it as a repository.

Remove the JsFormat plugin you have installed currently, edit you user package control settings and take the JsFormat entry out of the "repositories" array, then reinstall JsFormat from the `Install Package` menu.

This is being formatted correctly for me on the most recent version.

before formatting:
```javascript
function(){asdf();}

thing.default.foo();
promise.then(foo).finally(bar);
```

after formatting:
```javascript
function() {
	asdf();
}

thing.default.foo();
promise.then(foo).finally(bar);
```

**Comment by 0x80** [comment]
Thanks your instructions plus a restart worked for me. Everything seems to be fine now!

**Comment by 0x80** [comment]
What is the current version of JsBeautify used in JsFormat? I understand that from 1.5.2 it should ignore non javascript tags like html, and prevent messing up the formatting of JSX and Angular inline templates. For me this is still happening...
